version: '3.8'
services:
  react-app:
    build:
      context: .
      args:
        REACT_APP_ELEVENLABS_API_KEY: ${REACT_APP_ELEVENLABS_API_KEY}
        REACT_APP_KIMI_API_URL: ${REACT_APP_KIMI_API_URL}
        REACT_APP_MOONSHOT_KEY: ${REACT_APP_MOONSHOT_KEY}
        REACT_APP_SUPABASE_ANON_KEY: ${REACT_APP_SUPABASE_ANON_KEY}
        REACT_APP_SUPABASE_URL: ${REACT_APP_SUPABASE_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped 